doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodInterface: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethod

well_commerce_shipping:
    configuration:
        shipping_method:
            orm:
                factory: WellCommerce\Bundle\ShippingBundle\Factory\ShippingMethodFactory
                repository: WellCommerce\Bundle\ShippingBundle\Repository\ShippingMethodRepository
                mapping: "@WellCommerceShippingBundle/Resources/config/doctrine/ShippingMethod.orm.yml"
                entity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethod
            api:
                exposed: true
                dataset: shipping_method.dataset.admin
                manager: shipping_method.manager
        shipping_method_cost:
            orm:
                repository: WellCommerce\Bundle\ShippingBundle\Repository\ShippingMethodCostRepository
                mapping: "@WellCommerceShippingBundle/Resources/config/doctrine/ShippingMethodCost.orm.yml"
                entity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodCost
        shipping_method_translation:
            orm:
                mapping: "@WellCommerceShippingBundle/Resources/config/doctrine/ShippingMethodTranslation.orm.yml"
                entity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodTranslation
