# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    shipping_method.controller.admin:
        class: WellCommerce\Bundle\ShippingBundle\Controller\Admin\ShippingMethodController
        arguments: ['@shipping_method.manager', '@shipping_method.form_builder.admin', '@shipping_method.datagrid']
        calls:
            - [setContainer, ['@service_container']]
